config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: [:new, :create, :index, :show] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian], message: "%{value} is not a valid category" }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: (0..5)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
      # Continue working on this
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:address, :category, :name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def new
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  #   @review = Review.new
  # end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      # render restaurant_path(@restaurant), status: :unprocessable_entity
      render "restaurants/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
        <div class="navbar navbar-light">
          <%= link_to 'Home', restaurants_path, class:"btn btn-primary" %>
          <%= link_to 'Create', new_restaurant_path, class:"btn btn-primary" %>
        </div>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name  %>
  <%= f.input :category, error: "Pick a valid category" %>
  <%= f.input :address %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <ul>
    <% @restaurants.each do |restaurant| %>
    <li>
    <%= link_to restaurant.name, restaurant_path(restaurant) %>
    </li>
    <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-3">
  <%= render "restaurants/form" %>

</div>

app/views/restaurants/show.html.erb
<div class="container mt-3">

  <h1><%= @restaurant.name %></h1>
  <h2><%= @restaurant.category %></h2>
  <p><%= @restaurant.address %></p>

</div>
<div class="container mt-3">
  <%# <%= link_to "Add a review!", new_restaurant_review_path(@restaurant) %>
  <div class="d-flex justify-content-center flex-column align-items-center">
    <% if @restaurant.reviews.first %>
      <% @restaurant.reviews.each do |review| %>
      <div class = "w-50">
        <p><%= review.content %></p>
        <h3><%= review.rating %>/5</h3>
      </div>
      <% end %>
    <% else %>
       <h3>No review yet!</h3>
    <% end %>
    <%= render 'reviews/new' %>
  </div>
</div>

app/views/reviews/_new.html.erb
<div class="container mt-2">
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content, as: :text  %>
<%= f.input :rating, as: :integer, error: "Pick a valid number from 0 to 5" %>
<%= f.button :submit %>
<% end %>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content, as: :text  %>
<%= f.input :rating, as: :integer, error: "Pick a valid number from 0 to 5" %>
<%= f.button :submit %>
<% end %>